In [1]:
#13-03-2025
#Tournament is going on in that one of the team plays 9matches out of 9matches they won 4, 3 loss and 2 draw.   
total_matches = int(input('Enter Number of matches Playes: '))
won_matches = int(input('Enter Matches won: '))
loss_matches = int(input('Enter Matches loss: '))
draw_matches = int(input('Enter Matches Draw: '))
total_points = (3*(won_matches) + 0*(loss_matches) + 1*(draw_matches))
print(total_points)

Enter Number of matches Playes:  9
Enter Matches won:  4
Enter Matches loss:  3
Enter Matches Draw:  2


14


In [13]:
#Protien bar 
rasin = int(input('Enter the quantity of rasin: '))
almond = int(input('Enter the quantity of almond: '))
apricot = int(input('Enter the quantity of apricot: '))
total_weight = rasin + almond + apricot
rasin_perc = (rasin/total_weight)*100
print(rasin_perc)
almond_perc = (almond/total_weight)*100
print(almond_perc)
apricot_perc = (apricot/total_weight)*100
print(apricot_perc)

Enter the quantity of rasin:  50
Enter the quantity of almond:  60
Enter the quantity of apricot:  20


38.46153846153847
46.15384615384615
15.384615384615385


In [19]:
n = int(input('Enter the number: '))
if(n%2==0):
    print('Even')
else:
    print('Odd')

Enter the number:  12


Even


In [23]:
age = int(input('Enter your age: '))
if(age>18):
    print('You are Eligible to Vote.')
else:
    print('Not Eligible to Vote.')

Enter your age:  20


You are Eligible to Vote.


In [31]:
#prime number or not
n = int(input('Enter the number: '))
flag = 0
for i in range(2,n):
    if(n%i==0):
        print('It is not a prime.')
        flag=0
        break
    else:
        flag=1
if(flag==1):
    print('It is prime number.')
else:
    print('It is a consecutive number.')

Enter the number:  15


It is not a prime.
It is a consecutive number.


In [33]:
num1=int(input())
num2=int(input())
if(num1>num2):
    print(num1)
else:
    print(num2)

 10
 11


11


In [41]:
num=int(input('Enter the number: '))
if(num>0):
    print('Number is Positive.')
elif(num<0):
    print('Number is Negative.')
else:
    print('Number is Zero.')

Enter the number:  15


Number is Positive.


In [37]:
num=int(input())
if(num%5==0):
    print('Number is Divisible by 5.')
else:
    print('Number is Not Divisible by 5.')

 15


Number is Divisible by 5.


In [47]:
#greatest among three
a1=int(input('Enter the number: '))
a2=int(input('Enter the number: '))
a3=int(input('Enter the number: '))
if((a1>a2) and (a1>a3)):
    print('Number a1 is Greatest of among three numbers.')
elif((a2>a1) and (a2>a3)):
    print('Number a2 is Greatest of among three numbers.')
else:
    print('Number a3 is Greatest of among three numbers.')

Enter the number:  15
Enter the number:  20
Enter the number:  7


Number a2 is Greatest of among three numbers.


In [53]:
#ATM
account_balence = float(input('Enter the Current Balence: '))
withdraw_amount = int(input('Enter the amount to Withdraw: '))
remaining_balence = account_balence - withdraw_amount
if(withdraw_amount > account_balence):
    print('Insufficient Account Balence')
else:
    print('The current balence after withdrawal is: ',remaining_balence)

Enter the Current Balence:  50000.68
Enter the amount to Withdraw:  8075


The current balence after withdrawal is:  41925.68


In [1]:
import numpy as np                                             #13-03-2025

In [3]:
arr = np.array([2,3,4,5,6,7])
print(arr)

[2 3 4 5 6 7]


In [13]:
#2D Array is a comination od 2 1d arrays
arr = np.array([[1,2,3],[2,3,4]])
print(arr)

[[1 2 3]
 [2 3 4]]


In [15]:
#3D Array is a combination of 2 2d arrays
arr = np.array([[[10,11,12],[23,34,45]],[[21,65,56],[54,76,89]]])
print(arr)

[[[10 11 12]
  [23 34 45]]

 [[21 65 56]
  [54 76 89]]]


In [19]:
import numpy as np
import sys
s=[10,20,30,40,50,60,70,80,90,100]
print("Size of each element of list in python: ", sys.getsizeof(s))

b=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.size(b))

Size of each element of list in python:  136
10


In [21]:
[(a * b) for a,b in zip([1,2,3],[4,5,6])]

[4, 10, 18]

In [7]:
import numpy as np                                                                                         #14-03-2025
sai1=np.array([1,2])
sai2=np.array([[11,12],[13,14]])
sai3=np.array([[[11,12,13],[14,15,16]],[[17,18,19],[20,21,22]]])
print('The 1D Array: ')
print(sai1)
print('\n')
print('The 2D Array: ')
print(sai2)
print('\n')
print('The 3D Array: ')
print(sai3)

The 1D Array: 
[1 2]


The 2D Array: 
[[11 12]
 [13 14]]


The 3D Array: 
[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [ ]:
#Array Manipulations
np.transpose(array) --> to transpose an array
>>transpose()
It is an operator which flips a matrix over its diagonal, it switches the row and column indies of the matrix.It producing the another matrix i.e., A^T.

In [66]:
import numpy as np
n = np.array([[1, 2],[3, 4]])
print('Original Array:\n',n)
s = np.transpose(n)
print('Transposed Array:\n',s)

Original Array:
 [[1 2]
 [3 4]]
Transposed Array:
 [[1 3]
 [2 4]]


In [92]:
#reshape an array
n = np.array([80, 21, 32, 20, 3, 87])
print('The Original Array:\n',n)
print('The Reshaped Array:')
s = n.reshape(3,2)
print(s)

The Original Array:
 [80 21 32 20  3 87]
The Reshaped Array:
[[80 21]
 [32 20]
 [ 3 87]]


In [86]:
#Reshape an Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print('The Original Array:\n', arr)
reshaped_arr = arr.reshape(3, 4)
print('The Reshaped Array:\n', reshaped_arr)

The Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
The Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [96]:
#Resize an Array
n = np.array([80, 21, 32, 20, 3, 87])
print('The Original Array:\n',n)
print('Resized Array: ')
resize = np.resize(n, (3,2))
print(resize)

The Original Array:
 [80 21 32 20  3 87]
Resized Array: 
[[80 21]
 [32 20]
 [ 3 87]]


In [ ]:
#Flatten Array


In [ ]:
#NumpY Operatins in Python
np.insret() --> To insert an array
np.delete() --> delete an element from an array
np.append() --> append items to an array
np.unique() --> To get unique items from an array

In [ ]:
#INSERT to array
np.insert(arr,obj,values,axis) --> syntax
arr: Input Array
obj: The index before which insertion is to be made
values: The array of values to be inserted
axis: The axis along insert in given array, if not given, arr is flattend.

In [100]:
#create an array
a = np.random.randint(10,20,(2,3,4))
print(a)
print('The Shape of an array: \n', a.shape)

[[[12 19 14 13]
  [17 10 10 16]
  [10 16 19 19]]

 [[11 15 14 16]
  [16 17 19 11]
  [11 17 19 11]]]
The Shape of an array: 
 (2, 3, 4)


In [108]:
#insert values to an array
np.insert(a,1,50, axis=0)

array([[[12, 19, 14, 13],
        [17, 10, 10, 16],
        [10, 16, 19, 19]],

       [[50, 50, 50, 50],
        [50, 50, 50, 50],
        [50, 50, 50, 50]],

       [[11, 15, 14, 16],
        [16, 17, 19, 11],
        [11, 17, 19, 11]]])

In [104]:
np.insert(a,0,50, axis=1)

array([[[50, 50, 50, 50],
        [12, 19, 14, 13],
        [17, 10, 10, 16],
        [10, 16, 19, 19]],

       [[50, 50, 50, 50],
        [11, 15, 14, 16],
        [16, 17, 19, 11],
        [11, 17, 19, 11]]])

In [112]:
np.insert(a,3,50, axis=2)

array([[[12, 19, 14, 50, 13],
        [17, 10, 10, 50, 16],
        [10, 16, 19, 50, 19]],

       [[11, 15, 14, 50, 16],
        [16, 17, 19, 50, 11],
        [11, 17, 19, 50, 11]]])

In [ ]:
#APPEND to an array
np.append(arr,values,axis)

>>arr: Array
>>valuse: To be append to an arr. I t must be of the same shape as of arr(excluding axis of appending)
>>axis: The axis along which append operation is to be done. If not given, both parameters are flattend.

In [120]:
#creating an array
n = np.random.randint(2,6,(2,3,3))
print(n)
print('The shape of Array:\n', n.shape)

[[[2 4 5]
  [2 4 3]
  [3 5 3]]

 [[5 3 5]
  [2 4 3]
  [4 3 3]]]
The shape of Array:
 (2, 3, 3)


In [116]:
#appending to the array
np.append(n, 10)

array([ 3,  2,  2,  4,  5,  4,  3,  4,  3,  4,  3,  4,  2,  4,  4,  2,  3,
        5, 10])

In [118]:
#fix the axis other than axis of appending
n = np.random.randint(2,6,(2,1,3))
print(n)

[[[3 2 5]]

 [[4 2 2]]]


In [122]:
np.append(n,n,axis=1)

array([[[2, 4, 5],
        [2, 4, 3],
        [3, 5, 3],
        [2, 4, 5],
        [2, 4, 3],
        [3, 5, 3]],

       [[5, 3, 5],
        [2, 4, 3],
        [4, 3, 3],
        [5, 3, 5],
        [2, 4, 3],
        [4, 3, 3]]])

In [ ]:
#Delete a element from an array
np.delete(arr,values,axis) --> syntax
>>arr: Input array
>>obj: Can be a slice, an integer or array of untegers, indicating the subarray to be deleted from the input array.
>>axis: The axis along which to delete the given sub array.If not given, arr is flattend. 
>>Returns a copy of arr with the elements specified by obj removed. Note that delete does not occur in-place. If axis is None, out is a flattend array.