In [5]:
import numpy as np
#convert list to numpy array                              #17-03-2025
list = [1, 2, 3, 4, 5]
print("The Python list:\n", list)
a = np.array(list)
print("The Numpy Array:\n", a)

The Python list:
 [1, 2, 3, 4, 5]
The Numpy Array:
 [1 2 3 4 5]


In [15]:
#create 3*3 numpy array with zeroes
n=np.zeros((3,3))
print(n)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5,)


In [21]:
#create an array of 5 numbers from 0 and 1
n =np.array(np.random.randint(0,2,5))
print(n)

[1 0 1 0 0]


In [23]:
#reshape an array
arr = np.array([1,2,3,4,5,6])
print(arr)
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [25]:
#element wise addition
[(a + b) for a,b in zip([1,2,3],[4,5,6])]

[5, 7, 9]

In [27]:
#find max and min values
arr = np.array([3,7,2,9,5])
print(arr)
print("Maximum number in the array:\n", np.max(arr))
print("Minimum number in the array:\n", np.min(arr))

[3 7 2 9 5]
Maximum number in the array:
 9
Minimum number in the array:
 2


In [29]:
#mean and standard deviation
n = np.array([10,20,30,40,50])
print(n)
print("The mean of an array:\n", np.mean(n))
print("The standard deviation of an array:\n", np.std(n))

[10 20 30 40 50]
The mean of an array:
 30.0
The standard deviation of an array:
 14.142135623730951


In [35]:
#filter elements greater than 4 in an array
n = np.array([1,3,5,7,9])
print(n)
for num in n:
    if(num>4):
        print(num,end=" ")

[1 3 5 7 9]
5 7 9 

In [37]:
#multiply both arrays
a = np.array([[1,2],[3,4]])
s = np.array([[5,6],[7,8]])
print(np.matmul(a,s))   #matmul --> multiplication keyword
print(a@s)   # @ --> multiplication keyword(symbol)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [41]:
#create an array numbers from 1 to 10
n = np.array(np.random.randint(1,4,10))
print(n)

[3 1 3 2 2 2 2 3 1 1]
